apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'expo.modules.facelandmarker'
version = '0.1.0'

android {
  namespace 'expo.modules.facelandmarker'

  defaultConfig {
    minSdkVersion 23
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.google.mediapipe:tasks-vision:latest.release'
}
